### ISSUE TITLE
Error running quickstart

### ISSUE THREAD

**Issue by AechDub** [mixer/cdk#100]
### Error

Error: Unexpected status code 404 Not Found from https://mixercc.azureedge.net/launchpad/move-video: ﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:8a56ff96-901e-0128-0359-e2d...

### Editor Details

**Version**: 1.0.0
**Mixer User ID**: 594859

**Encrypted Editor State**: `{"id":"ab25ebfc835bef50","password":"nJEUPEko/vI8SHfH00d6m56cLVp+rHhD66r561RoCKY="}`

**Comment by connor4312** [comment]
This is because you put in `move-video` as the template under the advanced settings it looks like. This template does not exist, so the 404 is expected.

**Comment by AechDub** [comment]
Hmm....all I did was name it; not update the template.  Worked second time.  I'll close it :)
