### ISSUE TITLE
Ensure that NODE_ENV is set to development, or unset, while running the quickstart

### ISSUE THREAD

**Issue by SirNickParks** [mixer/cdk#103]
### Steps to Reproduce

Fresh install, created project (into a folder that was already created outside of the app), and then error appears.

Screenshot: https://cdn.discordapp.com/attachments/417259940734959616/442844480077561866/unknown.png

### Error

'webpack-dev-server' is not recognized as an internal or external command,
operable program or batch file.

### Editor Details

**Version**: 1.0.0
**Mixer User ID**: 930

**Comment by DeekyJay** [comment]
Node: 8.2.1
NPM: 5.7.1

**Comment by connor4312** [comment]
Thanks for the report! Can you list what's in the `node_modules/.bin` folder of your project?

**Comment by SirNickParks** [comment]
node_modules folder does not generate.

**Comment by connor4312** [comment]
Ok, thanks. Running `npm install` again within your project folder should fix this (and will be done automatically in #102). Assuming you created your project with the "New Project" wizard, did you notice any errors in that process?

**Comment by SirNickParks** [comment]
```
PS D:\RainbowSix-mixer\joyfully-exhausted-cow> npm -v
5.7.1
PS D:\RainbowSix-mixer\joyfully-exhausted-cow> node -v
v8.11.1
PS D:\RainbowSix-mixer\joyfully-exhausted-cow> npm install
npm WARN joyfully-exhausted-cow@0.1.0 No description
npm WARN joyfully-exhausted-cow@0.1.0 No repository field.

up to date in 0.05s
PS D:\RainbowSix-mixer\joyfully-exhausted-cow>
```

Output after updating node to LTS, still didn't generate a node_modules.

**Comment by DeekyJay** [comment]
Chatted a bit more with Nick. We determined it was the NODE_ENV set to production which skips installing dev dependencies. Perhaps we can force install dev dependencies since we do it automatically anyway 😄
