### ISSUE TITLE
Recent projects list issue

### ISSUE THREAD

**Issue by Skriglitz** [mixer/cdk#109]
### Steps to Reproduce

Create a project and close the project. Then move/delete the project folder, click the project in the recents list and a error will appear.

### Error

Projects that have been moved or deleted will appear in the recent projects section regardless of if still in the same location. Opening a deleted message will display a "File Not Found" error, while opening a moved project will show the same name in the recent list with no ability to tell which project is which. Needs 2 things added to help remedy this:

- Path preview to show the path to the project similar to how VS Code displays the path.
- Ability to remove a project from the recent list.

### Editor Details

**Version**: 1.0.0
**Mixer User ID**: 600014

**Encrypted Editor State**: `{"id":"690d6f30b40fdbf9","password":"jUV7p99vzzRFYFBM2U0qjbFIGeIee4nopt9EytskE2I="}`

**Comment by connor4312** [comment]
Fixed in the linked commit https://peet.io/i/18-05-b70qkahu88emrysqa7l88dt8sveb5f.mp4
