### ISSUE TITLE
Bundle Upload: I can't easily see or review warnings that go by quickly

### ISSUE THREAD

**Issue by gostay** [mixer/cdk#117]
Even on a successful bundle upload, I may have warnings that show up during the compile/upload process.  For instance, warnings about file sizes.  I can't easily see these after the upload completes, so if it's a fast upload, I just catch a glimpse of warnings before they go away.  Unlike with the webpack console, I can't go back and review the upload step output.  My current solution is quickly grabbing a screenshot before the window goes away, and hope there isn't scrolled output I need to see.  If there's a way to review this output, I don't know how.

**Comment by connor4312** [comment]
Good idea

![](https://peet.io/i/18-06-l0ry76mno8m0kuep7v3h49ooc01nvb.png)
