### ISSUE TITLE
"Unlink From" menu name is confusing - doesn't actually unlink?

### ISSUE THREAD

**Issue by gostay** [mixer/cdk#118]
The "Unlink from <projectname>" menu command actually brings up the interface for Linking to a project, which is a little confusing.  Did I unlink or not?  The answer seems to be that I did *not* unlink - it's just prompting me to replace my current link with a new link.

If this functionality is final, maybe the menu item should say "Link to another project"?

**Comment by connor4312** [comment]
Fixed in the linked commit. The menu is renamed "Change Linked Game" where you can now, actually, unlink the game you're linked to without linking to another one.
