### ISSUE TITLE
Force Restart in Webpack Console on failed compile requires two clicks

### ISSUE THREAD

**Issue by gostay** [mixer/cdk#120]
### Steps to Reproduce

* Load a project in the CDK
* outside the CDK, do some kind of rebuild that wipes the whole src directory and recreates it
* the webpack console gets stuck recompiling and shows an error ("couldn't find your homepage")
* Click "Force Restart" button.  Note that it doesn't do anything.
* Click "Force Restart" again.  This time it restarts.

### Error

First click on Force Restart does nothing, and I have to click it again.

### Editor Details

**Version**: 1.0.0
**Mixer User ID**: 32316796

**Encrypted Editor State**: `{"id":"fd7b45ca6ab7db0a","password":"hpstBkEzzoM/SJY3ECA/8ZpNzyeGvpQR5pCwACwqyVg="}`

**Comment by gostay** [comment]
This is pretty embarrassing, but I think my report is incorrect.  I think the first attempt just takes a couple of seconds to kick in, during which time the button is still there, so it only *looks* like my first click was ignored.  Sorry about that.  I double-checked before I submitted, but I guess I kept interpreting it wrong.

**Comment by connor4312** [comment]
We should fix that delay anyway. Thanks for the report!
