### ISSUE TITLE
The CDK should remember my window position

### ISSUE THREAD

**Issue by gostay** [mixer/cdk#121]
I carefully position my CDK window where I want it for effective debugging (relative to things like source windows, game client window, and devtools window).  The devtools window position is remembered, but I have to reposition the CDK window any time I've closed the CDK and reopened it.

It'd be nice if the CDK would remember my window position.  It'd probably be ideal if it remembered a unique position per project.

This is a very minor issue.

**Comment by connor4312** [comment]
Yea it's super annoying that it doesn't do this.

**Comment by connor4312** [comment]
Fixed in the linked commit
