### ISSUE TITLE
Linking to a project for which I have edit permissions

### ISSUE THREAD

**Issue by gostay** [mixer/cdk#128]
When linking to a project (for uploading a bundle), I should be able to select any project that I have edit privileges for.  The list of possible projects currently shows only projects I’ve created myself, but it would be very convenient (and make sense) if I got the same full list of projects I get when I’m logged in to mixer.com and looking at https://mixer.com/lab/interactive

We assume the point of allowing other people to edit interactive projects is to work together on something, and we see uploading a new bundle as a form of editing an interactive project.

**Comment by connor4312** [comment]
This has been requested by a few people, I'll get it in.

**Comment by connor4312** [comment]
Coming soon

![](https://peet.io/i/18-06-xng96hbcjr3lcpj6he94lg0ei0rbxr.png)
