### ISSUE TITLE
Build and Upload Controls fails even on clean project

### ISSUE THREAD

**Issue by yonteia** [mixer/cdk#142]
### Steps to Reproduce

1. Create new preact project.
2. Select **Build and Upload Controls**

### Error

Project builds locally fine via **Restart Webpack**, but errors out when trying to **Build and Upload Controls** showing the following error: 

> We ran into a problem compiling your controls. You can save the compilation output, which should contain more details about what went wrong.

Compilation output shows no errors:
[webpack-output-2018-09-04T20-29-38.457Z.txt](https://github.com/mixer/cdk/files/2350136/webpack-output-2018-09-04T20-29-38.457Z.txt)

Started having problems with my project, and, after testing with a clean new project, I found the problem was universal.

### Editor Details

**Version**: 1.0.1
**Mixer User ID**: 53919132

**Encrypted Editor State**: `{"id":"304d88821499bcad","password":"da2Roj8BJWls/lLHez8JqwQ3WeuPbykPfQ66bTAKq94="}`

**Comment by yonteia** [comment]
Messing around with network setting corrected the issue. The issue appears to have been with the upload, not with the compilation.

**Comment by connor4312** [comment]
Hi, thanks for reporting the issue! Azure is [having some issues](https://azure.microsoft.com/en-us/status/) at the moment in the region where our control data is stored. You may experience some issues authoring bundles until that clears up.
