### ISSUE TITLE
webpack-dev-server could not start

### ISSUE THREAD

**Issue by GabrieleNunez** [mixer/cdk#145]
### Steps to Reproduce

Just created a new full screen control project.

Tried to do some more research on my own, and I came up with these two links if it's any help:

- https://github.com/webpack/webpack/issues/8082
- https://github.com/webpack/webpack-cli/issues/607#issuecomment-424389911

I can confirm that updating my webpack-cli version to 3.1.1  fixes this issue

### Error

F:\MixerCustomControls\destiny-overlay\node_modules\webpack-cli\bin\config-yargs.js:89
				describe: optionsSchema.definitions.output.properties.path.description,
				                                           ^

TypeError: Cannot read property 'pro...

### Editor Details

**Version**: 1.0.2
**Mixer User ID**: 59192097

**Encrypted Editor State**: `{"id":"4a83bda37f27fe99","password":"FCBcdiJleOutSHItyvGiP2agvml1biqKe6m5PmFqLAA="}`

**Comment by connor4312** [comment]
Thanks for opening an issue, and sorry for the delayed response! It looks like a breaking change was made on a minor version in webpack (https://github.com/webpack/webpack/issues/8082) which caused the quick start templates to fail. You can either:

 - Re-create your project using the "new project" wizard -- we've updated the starter templates.
 - Update the version manually in an existing project:
    1. Edit your `package.json`. Replace the line containing `"webpack-cli":` with `"webpack-cli": "^3.1.2",`
    2. Either delete the `node_modules` folder in your project, or run `npm install`
    3. Restart the CDK if it's open.

Please let us know if you run into any more problems 🙂
