### ISSUE TITLE
Cannot create HTML or preact projects

### ISSUE THREAD

**Issue by Mobius5150** [mixer/cdk#146]
### Steps to Reproduce

Clone either HTML or preact starter project

### Error

clean-webpack-plugin: D:\Beam\stream-pet\stream-pet-control\build has been removed.
[34mi[39m [90m｢wds｣[39m: Project is running at [1m[34mhttp://localhost:13370/[39m[22m
[34mi[39m [90m｢wds｣[39m: webpack output is served from [1m[34m/[39m...

### Editor Details

**Version**: 1.0.2
**Mixer User ID**: 338492

**Encrypted Editor State**: `{"id":"7fcaa237dec2bfc8","password":"kmE7FNl6LLkL/G7d/HPfCAcNtlRU/gor1Bu+voz6GEc="}`

**Comment by connor4312** [comment]
Thanks for opening an issue, and sorry for the delayed response! It looks like a breaking change was made on a minor version in webpack (https://github.com/webpack/webpack/issues/8082) which caused the quick start templates to fail. You can either:

 - Re-create your project using the "new project" wizard -- we've updated the starter templates.
 - Update the version manually in an existing project:
    1. Edit your `package.json`. Replace the line containing `"webpack-cli":` with `"webpack-cli": "^3.1.2",`
    2. Either delete the `node_modules` folder in your project, or run `npm install`
    3. Restart the CDK if it's open.

Please let us know if you run into any more problems 🙂
